### ISSUE TITLE
[BUG] crash using ultrapermissions and hyperdrives

### ISSUE THREAD

**Issue by Sedrowow** [XZot1K/HyperDrive#23]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
1. open /warp.
2. Shift + right Click the warp to edit.
3. use the sign to change from public to private.

**Expected behavior**
it should block the users interaction or if permission given change it without using /op

**Actual behavior**
it causes a crash by ultrapermissions and hyperdrive

**Screenshots & Other Media**
none.

**Server Information (Please fill in the information below):**
 - Version: Paper 1.20.1
 - Plugins: [e.g. Essentials, HyperDrive, Vault, UltraPermissions, and some more non-interferring]

**Verification (REQUIRED - Only one is required):**
 - Spigot: Sedrowow
 - Version 5.5.3

**Additional context**
if i have operator it works fine, but if i dont have it, even though i've got the permissions set up, it causes a crash

**Comment by XZot1K** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the bug:
> 
> 1. open /warp.
> 2. Shift + right Click the warp to edit.
> 3. use the sign to change from public to private.
> 
> **Expected behavior** it should block the users interaction or if permission given change it without using /op
> 
> **Actual behavior** it causes a crash by ultrapermissions and hyperdrive
> 
> **Screenshots & Other Media** none.
> 
> **Server Information (Please fill in the information below):**
> 
> * Version: Paper 1.20.1
> * Plugins: [e.g. Essentials, HyperDrive, Vault, UltraPermissions, and some more non-interferring]
> 
> **Verification (REQUIRED - Only one is required):**
> 
> * Spigot: Sedrowow
> * Version 5.5.3
> 
> **Additional context** if i have operator it works fine, but if i dont have it, even though i've got the permissions set up, it causes a crash

There are new early builds of HyperDrive 5.5.4 on the Discord channel (accessible after verification). Looks like I resolved an issue earlier on with the permission checks. Feel free to reopen this if you have any questions!
