### ISSUE TITLE
Cross server warp/teleportation bug

### ISSUE THREAD

**Issue by iamharak** [XZot1K/HyperDrive#5]
Hello! I bought your plugin today and found an error. I want to use the plugin on the Bungee server, and the cross server teleportation/warp teleportation doesn't work as it should.

The plugin verifies the name of the world on the server I'm on and not the one I'm going to. Because of this, even if there are two identical world names between 2 servers, it will throw you in the wrong world and wrong position on the target server.

Otherwise, if the world name is not the same across theese two servers - i get an issue like this: https://prnt.sc/owkr1o

**Comment by XZot1K** [comment]
Do you have the MySQL settings and everything enabled correctly?

**Comment by iamharak** [comment]
Yeah, it looks like the settings are correct, since it creates all the necessary tables  without any problem at all, and later the plugin does fill these tables with data. However, the problem is that for some reason, it teleports me to wrong locations. But not randomly. I was able to figure out what the problem may be. Let's say I want to teleport to a warp from server A to server B.  The warp appears on both servers and looks 100% usable. But when I try to teleport to it, the plugin checks the location on server A before teleporting me to the other server (server B), and finds out that the specified world doesn't exist (which is in fact true as it's created only on server B), and this causes the teleportation process to be cancelled. When I create similarly named worlds on both A and B servers, it can teleport me cross-server, however I always end up at the location, where I left the server instead of the warp's location.

**Comment by XZot1K** [comment]
When you open up the warps table in the database, do both warps have separate IP addresses? Including the port.

**Comment by iamharak** [comment]
The warps are on the same ip address but on 2 different ports. 

It's not problem with the ip because you are teleporting to between the servers, just to wrong place because of controlling the world in the wrong place.

**Comment by XZot1K** [comment]
The plugin compares those IPs without fully pinging them, the way it functions is complex due to the avoidence of using Java Sockets. It normally tries to teleport the player in the same server if it thinks the IPs are the same. I'm exploring this issue, but I believe it is due to both servers running off that same IP that is causing the issue.

**Comment by XZot1K** [comment]
> 
> 
> The warps are on the same ip address but on 2 different ports.
> 
> It's not problem with the ip because you are teleporting to between the servers, just to wrong place because of controlling the world in the wrong place.

Oh wait, so you're making to the other server just not to the location?

**Comment by iamharak** [comment]
If the world of the warp exists on both servers, then yes, I can make through servers, but end up in a wrong location. When the world only exists on the target server, I cannot teleport anywhere.

**Comment by XZot1K** [comment]
> 
> 
> If the world of the warp exists on both servers, then yes, I can make through servers, but end up in a wrong location. When the world only exists on the target server, I cannot teleport anywhere.

Interesting I'll look further into this, it sounds like a check may just be misplaced.

**Comment by iamharak** [comment]
Hello, unfortunately the bug is the same in the latest version. (5.1.9)

I made a video of the bug: https://youtu.be/gSJBL6yJSqc


Pictures about the database:

Warps table: https://prnt.sc/oxku4j
https://prnt.sc/oxkucp

Transfer table: https://prnt.sc/oxkvzj
(Player stuck inside)


(The tables in the database are completely newly generated.)

**Comment by XZot1K** [comment]
Interesting it actually looks like it's working, but the warps in your table are overlapping all taking the coordinates of your first warp. I'm seeing if I replicate this issue!

**Comment by iamharak** [comment]
Picture of the new plugin version database: https://prnt.sc/oxsku6

Unfortunately the problem is the same.

**Comment by iamharak** [comment]
Checks the name of the world on the server I'm on and not on the server where the warp is. (I think that's the problem.)

**Comment by iamharak** [comment]
Ok, I send the friend request. (ScoterZ#6336)
