### ISSUE TITLE
Warp signs

### ISSUE THREAD

**Issue by sdkrocks** [XZot1K/HyperDrive#6]
I could be completly wrong on this - but I believe there are two permissions that should not be doing the same thing that are.

hyperdrive.use.signs
hyperdrive.use.createsigns

These both allow for the creation and use of signs. Is there any way to only allow the use of signs, and not creating them?

Thanks!

**Comment by XZot1K** [comment]
> I could be completly wrong on this - but I believe there are two permissions that should not be doing the same thing that are.
> 
> hyperdrive.use.signs
> hyperdrive.use.createsigns
> 
> These both allow for the creation and use of signs. Is there any way to only allow the use of signs, and not creating them?
> 
> Thanks!

Hey there, there is actually a typo on the page. The only real permission is "hyperdrive.use.signs". The old permission was to separate creation and usage of the signs. Currently the new permission above is the only one that handles both cases now.

**Comment by sdkrocks** [comment]
Is there a way currently to separate them?
My goal is to have them be able to teleport away using the signs - but not make signs wherever they'd like.
Thanks for the amazingly fast response!

**Comment by sdkrocks** [comment]
> > I could be completly wrong on this - but I believe there are two permissions that should not be doing the same thing that are.
> > hyperdrive.use.signs
> > hyperdrive.use.createsigns
> > These both allow for the creation and use of signs. Is there any way to only allow the use of signs, and not creating them?
> > Thanks!
> 
> Hey there, there is actually a typo on the page. The only real permission is "hyperdrive.use.signs". The old permission was to separate creation and usage of the signs. Currently the new permission above is the only one that handles both cases now.

Forgot to quote your reply ^^^

**Comment by XZot1K** [comment]
> Is there a way currently to separate them?
> My goal is to have them be able to teleport away using the signs - but not make signs wherever they'd like.
> Thanks for the amazingly fast response!



> > > I could be completly wrong on this - but I believe there are two permissions that should not be doing the same thing that are.
> > > hyperdrive.use.signs
> > > hyperdrive.use.createsigns
> > > These both allow for the creation and use of signs. Is there any way to only allow the use of signs, and not creating them?
> > > Thanks!
> > 
> > 
> > Hey there, there is actually a typo on the page. The only real permission is "hyperdrive.use.signs". The old permission was to separate creation and usage of the signs. Currently the new permission above is the only one that handles both cases now.
> 
> Forgot to quote your reply ^^^

Hey there, sorry for the late reply, So at the moment there is not since both actions seem to use that same permission. From the looks, it seems I replaced it unintentionally a while back, but nobody reported it. I will get that changed back here soon, I've been juggling plugins, but HyperDrive has an upcoming update! I always recommend joining the discord server for access to dev builds as I drop them!
