### ISSUE TITLE
feature request PremiumVanish support!  players can see Vanish player with group teleport.

### ISSUE THREAD

**Issue by rybuilder23** [XZot1K/HyperDrive#7]
if a player start a groupteleport you can choose the players in a gui menu.
And all online players are on that list even vanish players.

is it possible that you add support for vanish players and hide them?
i use PremiumVanish.

if you want more information i'm happy to help.
-- rybuilder23

**Comment by XZot1K** [comment]
> if a player start a groupteleport you can choose the players in a gui menu.
> And all online players are on that list even vanish players.
> 
> is it possible that you add support for vanish players and hide them?
> i use PremiumVanish.
> 
> if you want more information i'm happy to help.
> -- rybuilder23

I will take a look into the API of that plugin for you! :)
