### ISSUE TITLE
We need to FIX MYSQL asap

### ISSUE THREAD

**Issue by MaximeMichaud** [XZot1K/HyperDrive#8]
Since I don't remember, MYSQL have never working well.
5.3.9-B
`[HyperDrive] There was an issue saving the warp 'warzone' to the database (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(name, location, status, creation_date, icon_theme, animation_set, description_c' at line 1).
[21:09:20] [Craft Scheduler Thread - 8320/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(name, location, status, creation_date, icon_theme, animation_set, description_c' at line 1
[21:09:20] [Craft Scheduler Thread - 8320/WARN]: 	at sun.reflect.GeneratedConstructorAccessor182.newInstance(Unknown Source)`

And I don't remember the number of time that I erase everything. Just in case..

5.4 --->

https://hastebin.com/duvozanuca.md

I don't understand why you have default-ip + host

I put default-ip: IPV4 and HOST a DNS: A zone that is on the ipv4.
And that doesn't fix anything.
I get :
java.sql.SQLException: Access denied for user 'XXX_tp'@'XXX' (using password: YES)
The problem is that after @ .. the plugin put the hostname of the node that I am.
So the plugin disable himself because the MYSQL connection.

I tried MARIADB, MYSQL 5.7 + 8.0 and yet everything is not working well. I hoped that 5.4 fixed everything.

**Comment by XZot1K** [comment]
The syntax issue involving 5.3.9-B looks like a single warp failed to save, the syntax if the statement reference has been partially changed in 5.4, but this could be a variety of things. For example, a missing/deleted world. The second issue linked actually just states incorrect user information for the database. Double-check the username and password entered and then set the properties section to "properties: {}" this should block out any interference there. as for the "default-ip" this should be your gateway not the ipv4. The database "host" option is where your database ip needs to be alongside of port, user, etc.

**Comment by MaximeMichaud** [comment]
Indeed, idk why but that was happening same if I was deleting .db files.

What do you mean by "gateway" ?

**Comment by XZot1K** [comment]
> Indeed, idk why but that was happening same if I was deleting .db files.
> 
> What do you mean by "gateway" ?

Normally the gateway is 127.0.0.1 for most unless you have it set to 0.0.0.0!

**Comment by MaximeMichaud** [comment]
Doesn't work.
What I am doing, that is wrong ?
![image](https://user-images.githubusercontent.com/14856114/78460878-af812280-7692-11ea-88d8-53efdda5cce2.png)

**Comment by MaximeMichaud** [comment]
I disable MYSQL.
And I am getting :

```
[22:41:16]: [INFO] Mich issued server command: /spawn
[22:41:17]: [WARN] [HyperDrive] Task #647 for HyperDrive v5.4 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getChunkAtAsync(IIZ)Ljava/util/concurrent/CompletableFuture;
at xzot1k.plugins.hd.api.TeleportationHandler.run(TeleportationHandler.java:252) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[22:41:17]: [INFO] fightmaxime issued server command: /spawn
[22:41:18]: [INFO] fightmaxime issued server command: /spawn
[22:41:18]: [WARN] [HyperDrive] Task #647 for HyperDrive v5.4 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getChunkAtAsync(IIZ)Ljava/util/concurrent/CompletableFuture;
at xzot1k.plugins.hd.api.TeleportationHandler.run(TeleportationHandler.java:252) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by XZot1K** [comment]
> I disable MYSQL.
> And I am getting :
> 
> ```
> [22:41:16]: [INFO] Mich issued server command: /spawn
> [22:41:17]: [WARN] [HyperDrive] Task #647 for HyperDrive v5.4 generated an exception
> java.lang.NoSuchMethodError: org.bukkit.World.getChunkAtAsync(IIZ)Ljava/util/concurrent/CompletableFuture;
> at xzot1k.plugins.hd.api.TeleportationHandler.run(TeleportationHandler.java:252) ~[?:?]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
> [22:41:17]: [INFO] fightmaxime issued server command: /spawn
> [22:41:18]: [INFO] fightmaxime issued server command: /spawn
> [22:41:18]: [WARN] [HyperDrive] Task #647 for HyperDrive v5.4 generated an exception
> java.lang.NoSuchMethodError: org.bukkit.World.getChunkAtAsync(IIZ)Ljava/util/concurrent/CompletableFuture;
> at xzot1k.plugins.hd.api.TeleportationHandler.run(TeleportationHandler.java:252) ~[?:?]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
> at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
> ```

Oh that's not good, are you using normal spigot?

**Comment by MaximeMichaud** [comment]
Latest Paperspigot 1.8.8.
If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.

**Comment by XZot1K** [comment]
> Latest Paperspigot 1.8.8.
> If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.

That is weird, alright, so 1.8.8 spigot doesn't have an async chunk method apparently. I'm checking into this to see if it is maybe under another name.

**Comment by MaximeMichaud** [comment]
> > Latest Paperspigot 1.8.8.
> > If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.
> 
> That is weird, alright, so 1.8.8 spigot doesn't have an async chunk method apparently. I'm checking into this to see if it is maybe under another name.

Ok, let me know !

**Comment by XZot1K** [comment]
> > > Latest Paperspigot 1.8.8.
> > > If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.
> > 
> > 
> > That is weird, alright, so 1.8.8 spigot doesn't have an async chunk method apparently. I'm checking into this to see if it is maybe under another name.
> 
> Ok, let me know !

This is for me: https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0006-Add-async-chunk-load-API.patch but it looks like the method has an extra parameter in this. If you haven't already hop in the discord and get verified! I will be dropping a dev build for a potential fix!

**Comment by MaximeMichaud** [comment]
> > > > Latest Paperspigot 1.8.8.
> > > > If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.
> > > 
> > > 
> > > That is weird, alright, so 1.8.8 spigot doesn't have an async chunk method apparently. I'm checking into this to see if it is maybe under another name.
> > 
> > 
> > Ok, let me know !
> 
> This is for me: https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0006-Add-async-chunk-load-API.patch but it looks like the method has an extra parameter in this. If you haven't already hop in the discord and get verified! I will be dropping a dev build for a potential fix!

I will join the Discord.
I don't have the resources other than GitHub.

**Comment by XZot1K** [comment]
> > > > > Latest Paperspigot 1.8.8.
> > > > > If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.
> > > > 
> > > > 
> > > > That is weird, alright, so 1.8.8 spigot doesn't have an async chunk method apparently. I'm checking into this to see if it is maybe under another name.
> > > 
> > > 
> > > Ok, let me know !
> > 
> > 
> > This is for me: https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0006-Add-async-chunk-load-API.patch but it looks like the method has an extra parameter in this. If you haven't already hop in the discord and get verified! I will be dropping a dev build for a potential fix!
> 
> I will join the Discord.
> I don't have the resources other than GitHub.

I have a dev. build in the discord server which attempts to resolve that issue, that particular issue seems to fix with those changes!

**Comment by MaximeMichaud** [comment]
> > > > > > Latest Paperspigot 1.8.8.
> > > > > > If you remember, I had a problem with the latest SimplePortals 1.4.5, so I am using 1.4.3 right now.
> > > > > 
> > > > > 
> > > > > That is weird, alright, so 1.8.8 spigot doesn't have an async chunk method apparently. I'm checking into this to see if it is maybe under another name.
> > > > 
> > > > 
> > > > Ok, let me know !
> > > 
> > > 
> > > This is for me: https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0006-Add-async-chunk-load-API.patch but it looks like the method has an extra parameter in this. If you haven't already hop in the discord and get verified! I will be dropping a dev build for a potential fix!
> > 
> > 
> > I will join the Discord.
> > I don't have the resources other than GitHub.
> 
> I have a dev. build in the discord server which attempts to resolve that issue, that particular issue seems to fix with those changes!

Give me this Build and swear that MYSQL will work fine. And I buy your plugin without any Easter promotion. 
Mich#9194
